# Generated by Django 6.1.1 on 2026-09-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_unique_lesson_order_per_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
